---
framework: jest
preRun:
  command:
    - npm ci
preMerge:
  pattern:
    - "./src/core/utils/*.test.js"
postMerge:
  pattern: 
    - "./src/core/utils/*.test.js"
postRun:
  command:
    - node --version
version: 1.0
